expect

diff --git a/t/progression b/t/progression
--- a/t/progression
+++ b/t/progression
@@ -12,6 +12,7 @@ difs () {
     declare -i errs=0
     for f in tests/*.input.txt; do
         name="$(basename "${f%.input.txt}")"
+        [[ ${name} = *${namefilter}* ]] || continue
         dif1 "${ref}" "${name}" || (( errs++ ))
     done
     return ${errs}
@@ -28,9 +29,9 @@ dif1 () {
     ref=$1
     name=$2
     case ${ref} in
-        expected) colorspec=bcyan,green
+        expected) colorspec=green,bcyan
                   reffile=tests/out/"${name}.${step}".expected.txt ;;
-        gold) colorspec=bcyan,brown
+        gold) colorspec=brown,bcyan
               reffile=tests/"${name}.${step}".gold.txt ;;
         *)
             echo "ERROR bug in call to dif1" >&2; exit 1 ;;
@@ -38,8 +39,8 @@ dif1 () {
     (
         set -o pipefail
         diff -U0 -I'^swe-nor\|AP_SRC'                  \
-             tests/out/"${name}"."${step}".current.txt \
              "${reffile}"                              \
+             tests/out/"${name}"."${step}".current.txt \
             | wdif "${colorspec}"
     )
 }
@@ -47,6 +48,7 @@ dif1 () {
 assert-translated () {
     for f in tests/*.input.txt; do
         name="$(basename "${f%.input.txt}")"
+        [[ ${name} = *${namefilter}* ]] || continue
         cur=tests/out/"${name}"."${step}".current.txt
         if [[ ! -f "${cur}" ]]; then
             echo "${cur} not found" >&2
@@ -64,32 +66,48 @@ $0 translate      # run this after your edits and compiles
 $0 diff-expected  # compare result of 'translate' with expected output
 $0 diff-gold      # compare result of 'translate' with gold set
 $0 update         # update the current expected output with result of 'translate'
+$0 expect         # add sentence from stdin as new test with current as expected
 "
     exit 1
 }
 
-[[ $# -ne 1 ]] && assert-usage
+
+[[ $# -lt 1 || $# -gt 2 ]] && assert-usage
+
+namefilter=''
+[[ $# -ge 2 ]] && namefilter=$2
 
 case $1 in
     translate)
         for f in tests/*.input.txt; do
             name="$(basename "${f%.input.txt}")"
+            [[ ${name} = *${namefilter}* ]] || continue
             apertium -d . "${mode}" < tests/"${name}".input.txt >tests/out/"${name}.${step}".current.txt
         done
         ;;
     update)
-        assert-translated
+        assert-translated "${namefilter}"
         for cur in tests/out/*."${step}".current.txt; do
             cp -v "${cur}" "${cur%current.txt}expected.txt"
         done
         ;;
     diff-expected)
-        assert-translated
-        difs expected
+        assert-translated "${namefilter}"
+        difs expected "${namefilter}"
         ;;
     diff-gold)
-        assert-translated
-        difs gold
+        assert-translated "${namefilter}"
+        difs gold "${namefilter}"
+        ;;
+    expect)
+        if [[ -z "${namefilter}" ]]; then echo "Needs a test set, e.g. 'ymse'"; exit 1; fi
+        inputf=tests/"${namefilter}"-${mode}.input.txt
+        expf=tests/out/"${namefilter}"-${mode}.all.expected.txt
+        goldf=tests/"${namefilter}"-${mode}.all.gold.txt
+        if [[ ! -e "${inputf}" ]]; then echo "Unknown test set '${namefilter}'"; echo "(couldn't find file ${inputf} – try 'ymse' if unsure)"; exit 1; fi
+        input=$(cat)
+        [[ "${input}" = *[.?\!] ]] || input="${input}." # ensure final punctuation
+        echo "${input}" | tee -a "${inputf}" | apertium -d . "${mode}" | tee -a "${expf}" "${goldf}"
         ;;
     *)
         assert-usage
